version: 0.2

phases:
    build:
        commands:
         - echo Entered build phase (building...)
         - mvn clean package
    post_build:
        commands:
            - echo Build completed successfully
artifacts:
    files:
     - target/meto-backend.jar
    discard-paths: yes